/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.daointerface;

// auto generated imports
import com.bbd.bdsso.common.dal.dataobject.SsoAppDO;
import org.springframework.dao.DataAccessException;

/**
 * A dao interface provides methods to access database table <tt>sso_app</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_app.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public interface SsoAppDAO {
	/**
	 *  Insert one <tt>SsoAppDO</tt> object to DB table <tt>sso_app</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sso_app(app_name,app_pic,app_logo,is_enable,description,last_modifier,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param ssoApp
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
    public Integer insert(SsoAppDO ssoApp) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_app</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_app where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(Integer id) throws DataAccessException;

	/**
	 *  Update DB table <tt>sso_app</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sso_app set app_name=?, app_pic=?, app_logo=?, is_enable=?, description=?, last_modifier=?, gmt_modified=? where (id = ?)</tt>
	 *
	 *	@param ssoApp
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SsoAppDO ssoApp) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_app</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_name, app_pic, app_logo, is_enable, description, last_modifier, gmt_create, gmt_modified from sso_app where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SsoAppDO
	 *	@throws DataAccessException
	 */	 
    public SsoAppDO query(Integer id) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_app</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, app_name, app_pic, app_logo, is_enable, description, last_modifier, gmt_create, gmt_modified from sso_app where (app_name = ?)</tt>
	 *
	 *	@param appName
	 *	@return SsoAppDO
	 *	@throws DataAccessException
	 */	 
    public SsoAppDO queryByName(String appName) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_app</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_app where (description LIKE ?)</tt>
	 *
	 *	@param description
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByDesc(String description) throws DataAccessException;

}