/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.daointerface;

// auto generated imports
import com.bbd.bdsso.common.dal.dataobject.SsoRoleDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>sso_role</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_role.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public interface SsoRoleDAO {
	/**
	 *  Insert one <tt>SsoRoleDO</tt> object to DB table <tt>sso_role</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sso_role(role_name,is_enable,description,last_modifier,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param ssoRole
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
    public Integer insert(SsoRoleDO ssoRole) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_role</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(Integer id) throws DataAccessException;

	/**
	 *  Update DB table <tt>sso_role</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sso_role set role_name=?, is_enable=?, description=?, last_modifier=?, gmt_modified=? where (id = ?)</tt>
	 *
	 *	@param ssoRole
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SsoRoleDO ssoRole) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_name, is_enable, description, last_modifier, gmt_create, gmt_modified from sso_role where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SsoRoleDO
	 *	@throws DataAccessException
	 */	 
    public SsoRoleDO query(Integer id) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_name, is_enable, description, last_modifier, gmt_create, gmt_modified from sso_role where (role_name = ?)</tt>
	 *
	 *	@param roleName
	 *	@return SsoRoleDO
	 *	@throws DataAccessException
	 */	 
    public SsoRoleDO queryByRoleName(String roleName) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select b.id id, b.role_name role_name, b.is_enable is_enable, c.description description, b.last_modifier last_modifier, b.gmt_create gmt_create, b.gmt_modified gmt_modified from sso_user a, sso_role b, sso_user_role c where ((a.id = c.user_id) AND (b.id = c.role_id))</tt>
	 *
	 *	@param userName
	 *	@return List<SsoRoleDO>
	 *	@throws DataAccessException
	 */	 
    public List<SsoRoleDO> queryByUserName(String userName) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_role</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role where (description LIKE ?)</tt>
	 *
	 *	@param description
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByDesc(String description) throws DataAccessException;

}