/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.daointerface;

// auto generated imports
import com.bbd.bdsso.common.dal.dataobject.SsoRoleAuthDO;
import org.springframework.dao.DataAccessException;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>sso_role_auth</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_role_auth.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public interface SsoRoleAuthDAO {
	/**
	 *  Insert one <tt>SsoRoleAuthDO</tt> object to DB table <tt>sso_role_auth</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sso_role_auth(role_id,auth_id,description,last_modifier,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param ssoRoleAuth
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
    public Integer insert(SsoRoleAuthDO ssoRoleAuth) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(Integer id) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where (role_id = ?)</tt>
	 *
	 *	@param roleId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRoleId(Integer roleId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where ((role_id = ?) AND (auth_id = ?))</tt>
	 *
	 *	@param roleId
	 *	@param authId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRoleIdAndAuthId(Integer roleId, Integer authId) throws DataAccessException;

	/**
	 *  Update DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sso_role_auth set role_id=?, auth_id=?, description=?, last_modifier=?, gmt_modified=? where (id = ?)</tt>
	 *
	 *	@param ssoRoleAuth
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SsoRoleAuthDO ssoRoleAuth) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SsoRoleAuthDO
	 *	@throws DataAccessException
	 */	 
    public SsoRoleAuthDO query(Integer id) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where (role_id = ?)</tt>
	 *
	 *	@param roleId
	 *	@return List<SsoRoleAuthDO>
	 *	@throws DataAccessException
	 */	 
    public List<SsoRoleAuthDO> queryByRoleId(Integer roleId) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where (auth_id = ?)</tt>
	 *
	 *	@param authId
	 *	@return List<SsoRoleAuthDO>
	 *	@throws DataAccessException
	 */	 
    public List<SsoRoleAuthDO> queryByAuthId(Integer authId) throws DataAccessException;

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where ((role_id = ?) AND (auth_id = ?))</tt>
	 *
	 *	@param roleId
	 *	@param authId
	 *	@return SsoRoleAuthDO
	 *	@throws DataAccessException
	 */	 
    public SsoRoleAuthDO queryByRoleIdAndAuthId(Integer roleId, Integer authId) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where (description LIKE ?)</tt>
	 *
	 *	@param description
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByDesc(String description) throws DataAccessException;

}