/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.dataobject;

import java.io.Serializable;
// auto generated imports
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>sso_account_valid</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_account_valid.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public class SsoAccountValidDO implements Serializable {

	/** serialId */
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private Integer id;

	/**
	 * This property corresponds to db column <tt>email</tt>.
	 */
	private String email;

	/**
	 * This property corresponds to db column <tt>verify_code</tt>.
	 */
	private String verifyCode;

	/**
	 * This property corresponds to db column <tt>is_verified</tt>.
	 */
	private int isVerified;

	/**
	 * This property corresponds to db column <tt>type</tt>.
	 */
	private int type;

	/**
	 * This property corresponds to db column <tt>valid_date</tt>.
	 */
	private Date validDate;

	/**
	 * This property corresponds to db column <tt>description</tt>.
	 */
	private String description;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public Integer getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(Integer id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>email</tt>.
     *
     * @return property value of email
     */
	public String getEmail() {
		return email;
	}
	
	/**
	 * Setter method for property <tt>email</tt>.
	 * 
	 * @param email value to be assigned to property email
     */
	public void setEmail(String email) {
		this.email = email;
	}

    /**
     * Getter method for property <tt>verifyCode</tt>.
     *
     * @return property value of verifyCode
     */
	public String getVerifyCode() {
		return verifyCode;
	}
	
	/**
	 * Setter method for property <tt>verifyCode</tt>.
	 * 
	 * @param verifyCode value to be assigned to property verifyCode
     */
	public void setVerifyCode(String verifyCode) {
		this.verifyCode = verifyCode;
	}

    /**
     * Getter method for property <tt>isVerified</tt>.
     *
     * @return property value of isVerified
     */
	public int getIsVerified() {
		return isVerified;
	}
	
	/**
	 * Setter method for property <tt>isVerified</tt>.
	 * 
	 * @param isVerified value to be assigned to property isVerified
     */
	public void setIsVerified(int isVerified) {
		this.isVerified = isVerified;
	}

    /**
     * Getter method for property <tt>type</tt>.
     *
     * @return property value of type
     */
	public int getType() {
		return type;
	}
	
	/**
	 * Setter method for property <tt>type</tt>.
	 * 
	 * @param type value to be assigned to property type
     */
	public void setType(int type) {
		this.type = type;
	}

    /**
     * Getter method for property <tt>validDate</tt>.
     *
     * @return property value of validDate
     */
	public Date getValidDate() {
		return validDate;
	}
	
	/**
	 * Setter method for property <tt>validDate</tt>.
	 * 
	 * @param validDate value to be assigned to property validDate
     */
	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

    /**
     * Getter method for property <tt>description</tt>.
     *
     * @return property value of description
     */
	public String getDescription() {
		return description;
	}
	
	/**
	 * Setter method for property <tt>description</tt>.
	 * 
	 * @param description value to be assigned to property description
     */
	public void setDescription(String description) {
		this.description = description;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /** 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
