/*
 * bbdservice.com Inc.
 * Copyright (c) 2017 All Rights Reserved.
 */
package com.bbd.bdsso.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.bbd.bdsso.common.dal.daointerface.SsoRoleAuthDAO;

// auto generated imports
import com.bbd.bdsso.common.dal.dataobject.SsoRoleAuthDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import com.bbd.bdsso.common.dal.dataobject.SsoRoleAuthDO;

/**
 * An ibatis based implementation of dao interface <tt>com.bbd.bdsso.common.dal.daointerface.SsoRoleAuthDAO</tt>.
 *
 * This file is generated by <tt>bdsso-bbdalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bdsso</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/bbdalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sso_role_auth.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bdsso-bbdalgen</tt> 
 * to generate this file.
 *
 * @author Byron Zhang
 * @version $Id: description-java.vm,v 1.1 2016/05/01 07:34:20 byron Exp $
 */
public class IbatisSsoRoleAuthDAO extends SqlMapClientDaoSupport implements SsoRoleAuthDAO {
	/**
	 *  Insert one <tt>SsoRoleAuthDO</tt> object to DB table <tt>sso_role_auth</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sso_role_auth(role_id,auth_id,description,last_modifier,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param ssoRoleAuth
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
    public Integer insert(SsoRoleAuthDO ssoRoleAuth) throws DataAccessException {
    	if (ssoRoleAuth == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-SSO-ROLE-AUTH-INSERT", ssoRoleAuth);

        return ssoRoleAuth.getId();
    }

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(Integer id) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-SSO-ROLE-AUTH-DELETE", id);
    }

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where (role_id = ?)</tt>
	 *
	 *	@param roleId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRoleId(Integer roleId) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-SSO-ROLE-AUTH-DELETE-BY-ROLE-ID", roleId);
    }

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where ((role_id = ?) AND (auth_id = ?))</tt>
	 *
	 *	@param roleId
	 *	@param authId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByRoleIdAndAuthId(Integer roleId, Integer authId) throws DataAccessException {
        Map param = new HashMap();

        param.put("roleId", roleId);
        param.put("authId", authId);

        return getSqlMapClientTemplate().delete("MS-SSO-ROLE-AUTH-DELETE-BY-ROLE-ID-AND-AUTH-ID", param);
    }

	/**
	 *  Update DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sso_role_auth set role_id=?, auth_id=?, description=?, last_modifier=?, gmt_modified=? where (id = ?)</tt>
	 *
	 *	@param ssoRoleAuth
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SsoRoleAuthDO ssoRoleAuth) throws DataAccessException {
    	if (ssoRoleAuth == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return getSqlMapClientTemplate().update("MS-SSO-ROLE-AUTH-UPDATE", ssoRoleAuth);
    }

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SsoRoleAuthDO
	 *	@throws DataAccessException
	 */	 
    public SsoRoleAuthDO query(Integer id) throws DataAccessException {

        return (SsoRoleAuthDO) getSqlMapClientTemplate().queryForObject("MS-SSO-ROLE-AUTH-QUERY", id);

    }

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where (role_id = ?)</tt>
	 *
	 *	@param roleId
	 *	@return List<SsoRoleAuthDO>
	 *	@throws DataAccessException
	 */	 
    public List<SsoRoleAuthDO> queryByRoleId(Integer roleId) throws DataAccessException {

        return getSqlMapClientTemplate().queryForList("MS-SSO-ROLE-AUTH-QUERY-BY-ROLE-ID", roleId);

    }

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where (auth_id = ?)</tt>
	 *
	 *	@param authId
	 *	@return List<SsoRoleAuthDO>
	 *	@throws DataAccessException
	 */	 
    public List<SsoRoleAuthDO> queryByAuthId(Integer authId) throws DataAccessException {

        return getSqlMapClientTemplate().queryForList("MS-SSO-ROLE-AUTH-QUERY-BY-AUTH-ID", authId);

    }

	/**
	 *  Query DB table <tt>sso_role_auth</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, role_id, auth_id, description, last_modifier, gmt_create, gmt_modified from sso_role_auth where ((role_id = ?) AND (auth_id = ?))</tt>
	 *
	 *	@param roleId
	 *	@param authId
	 *	@return SsoRoleAuthDO
	 *	@throws DataAccessException
	 */	 
    public SsoRoleAuthDO queryByRoleIdAndAuthId(Integer roleId, Integer authId) throws DataAccessException {
        Map param = new HashMap();

        param.put("roleId", roleId);
        param.put("authId", authId);

        return (SsoRoleAuthDO) getSqlMapClientTemplate().queryForObject("MS-SSO-ROLE-AUTH-QUERY-BY-ROLE-ID-AND-AUTH-ID", param);

    }

	/**
	 *  Delete records from DB table <tt>sso_role_auth</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sso_role_auth where (description LIKE ?)</tt>
	 *
	 *	@param description
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteByDesc(String description) throws DataAccessException {

        return getSqlMapClientTemplate().delete("MS-SSO-ROLE-AUTH-DELETE-BY-DESC", description);
    }

}